// DONT EDIT - generated by extractcodefromvfx panorama.vfx

#pragma once

struct FastBlurFilterParams_t
{
	float m_flCenterWeight;
	float m_flPad0;
	float m_flPad1;
	float m_flPad2;
	Vector4D m_vSample1;
	Vector4D m_vSample2;
	Vector4D m_vSample3;
	Vector4D m_vSample4;
	Vector4D m_vSample5;
	Vector4D m_vSample6;
	Vector4D m_vSample7;
	Vector4D m_vSample8;
};
