// DONT EDIT - generated by extractcodefromvfx panorama_fancyquad.vfx

#pragma once

struct FancyQuadCoreConstants_t
{
	Vector4D m_vOutercornerradii0;
	Vector4D m_vOutercornerradii1;
	Vector4D m_vInnercornerradii0;
	Vector4D m_vInnercornerradii1;
	
	Vector4D m_vBordercolor;
	
	float m_flHueShift;
	float m_flSaturation;
	float m_flBrightness;
	float m_flContrast;
	
	Vector2D m_vGradientradialoffset;
	
	float m_flOpacityMaskOpacity;
};
struct FancyQuadRadialClipConstants_t
{
	float m_flRadialClipCenterX;
	float m_flRadialClipCenterY;
	float m_flRadialClipBlendStepX;
	float m_flRadialClipBlendStepY;
	float m_flRadialClipStartAngle;
	float m_flRadialClipSectorAngle;
};
