"""Independent file/codec helpers for regression tests and quality reports."""
from pathlib import Path
import io
import json
import math
import struct
import subprocess
import numpy as np
from PIL import Image


def run(*args, ok=True):
    result = subprocess.run([str(a) for a in args], capture_output=True, text=True)
    if ok and result.returncode:
        raise AssertionError(f'{args}: exit {result.returncode}\n{result.stdout}\n{result.stderr}')
    return result


def ktx_info(path):
    data = Path(path).read_bytes()
    assert data[:12] == b'\xabKTX 20\xbb\r\n\x1a\n'
    values = struct.unpack_from('<13I2Q', data, 12)
    names = ('format', 'type_size', 'width', 'height', 'depth', 'layers', 'faces', 'mips',
             'supercompression', 'dfd_offset', 'dfd_length', 'kvd_offset', 'kvd_length',
             'sgd_offset', 'sgd_length')
    result = dict(zip(names, values))
    result['levels'] = [struct.unpack_from('<3Q', data, 80 + i * 24) for i in range(result['mips'])]
    result['metadata'] = {}
    offset = result['kvd_offset']
    end = offset + result['kvd_length']
    while offset < end:
        length = struct.unpack_from('<I', data, offset)[0]
        key, value = data[offset + 4:offset + 4 + length].split(b'\0', 1)
        result['metadata'][key.decode()] = value
        offset += 4 + (length + 3) // 4 * 4
    result['data'] = data
    return result


def validate_ktx(validator, path):
    result = run(validator, 'validate', '--format', 'mini-json', path)
    report = json.loads(result.stdout)
    assert report['valid'], report
    # Application metadata is permitted by KTX2; Khronos reports it as warning 7010.
    assert all(m['id'] == 7010 and m['type'] == 'warning' for m in report['messages']), report
    return report


def decode_astc(cli, path, out, mip=0, frame=0, face=0):
    info = ktx_info(path)
    block = {157: 4, 158: 4, 165: 6, 166: 6, 171: 8, 172: 8}[info['format']]
    width, height = max(1, info['width'] >> mip), max(1, info['height'] >> mip)
    image_size = math.ceil(width / block) * math.ceil(height / block) * 16
    offset, size, _ = info['levels'][mip]
    assert size == image_size * max(1, info['layers']) * info['faces']
    offset += (frame * info['faces'] + face) * image_size
    astc_path = Path(out).with_suffix('.astc')
    header = struct.pack('<I3B', 0x5ca1ab13, block, block, 1)
    header += width.to_bytes(3, 'little') + height.to_bytes(3, 'little') + (1).to_bytes(3, 'little')
    astc_path.write_bytes(header + info['data'][offset:offset + image_size])
    mode = '-ds' if info['format'] in (158, 166, 172) else '-dl'
    run(cli, mode, astc_path, out, '-silent')
    return np.array(Image.open(out).convert('RGBA'))


def decode_dds(payload, width, height, fourcc):
    # Pillow's independent BC decoder; VTF's top-level block stream is also valid DDS data.
    header = struct.pack('<7I', 124, 0x81007, height, width, len(payload), 0, 0)
    header += bytes(44)
    header += struct.pack('<II4s5I', 32, 4, fourcc, 0, 0, 0, 0, 0)
    header += struct.pack('<5I', 0x1000, 0, 0, 0, 0)
    assert len(header) == 124
    return np.array(Image.open(io.BytesIO(b'DDS ' + header + payload)).convert('RGBA'))


def make_vtf(width=4, height=4, fmt=0, mip_count=1, frames=1, faces=1, depth=1,
             minor=5, thumbnail=False, stored_faces=None, payload=None, flags=0):
    """Synthetic files with explicit per-subresource bytes, not generated by the converter."""
    stored_faces = stored_faces or faces
    low = struct.pack('<HHI', 0xf800, 0, 0) if thumbnail else b''
    header_size = (96 if thumbnail else 88) if minor >= 3 else 80
    header = bytearray(header_size)
    struct.pack_into('<4s3I', header, 0, b'VTF\0', 7, minor, header_size)
    struct.pack_into('<HHIHH', header, 16, width, height, flags | (0x4000 if faces == 6 else 0), frames, 0)
    struct.pack_into('<3f', header, 32, .2, .3, .4)
    struct.pack_into('<f', header, 48, 1.0)
    struct.pack_into('<IBiBB', header, 52, fmt, mip_count, 13 if thumbnail else -1, 4 if thumbnail else 0, 4 if thumbnail else 0)
    if minor >= 2:
        struct.pack_into('<H', header, 63, depth)
    if minor >= 3:
        struct.pack_into('<I', header, 68, 2 if thumbnail else 1)
        struct.pack_into('<II', header, 80, 0x30, header_size + len(low))
        if thumbnail:
            struct.pack_into('<II', header, 88, 1, header_size)
    images = []
    for mip in reversed(range(mip_count)):
        w, h, d = max(1, width >> mip), max(1, height >> mip), max(1, depth >> mip)
        stored_depth = 4 if fmt in (13, 14, 15, 20, 34, 35) and 1 < d < 4 else d
        for frame in range(frames):
            for face in range(stored_faces):
                for z in range(stored_depth):
                    if payload:
                        part = payload(mip, frame, face, z, w, h)
                    else:
                        color = bytes((20 + mip * 30, 30 + frame * 60, 40 + face * 25 + z * 15, 255))
                        part = color * (w * h)
                    images.append(part)
    return bytes(header) + low + b''.join(images)
