#!/usr/bin/env python3
"""Generate the stable pre-device interfaces from the checked Source ABI slots."""

from pathlib import Path
import re
import sys


def arguments(declaration):
    if declaration.strip() in ("", "void"):
        return declaration, ""
    declarations, names = [], []
    for index, argument in enumerate(declaration.split(",")):
        argument = argument.split("=", 1)[0].strip()
        name = re.search(r"([A-Za-z_]\w*)\s*(\[[^]]*\])?$", argument)
        if not name or not argument[:name.start()].strip():
            argument += " arg" + str(index)
            name = re.search(r"([A-Za-z_]\w*)$", argument)
        declarations.append(argument)
        names.append(name.group(1))
    return ", ".join(declarations), ", ".join(names)


def method(result, name, parameters, suffix, target):
    if name == "Printf":
        return ("    void Printf(char* fmt, ...) override { va_list args; va_start(args, fmt); "
                + target + "().PrintfVA(fmt, args); va_end(args); }")
    declaration, call = arguments(parameters)
    return f"    {result} {name}({declaration}) {suffix} override {{ return {target}().{name}({call}); }}"


def main():
    root = Path(__file__).resolve().parent
    output = ["// Generated by generate-interface-proxies.py. Do not edit.", "#pragma once", ""]
    output += ["class ModuleAPIForwarder : public IShaderAPI {", "public:"]
    api = re.findall(r"^\s+(.+?)\b(\w+)\((.*?)\)\s*(const)?\s*override\s*\{", 
                     (root / "vulkan_api_unsupported.h").read_text(), re.MULTILINE)
    if not 250 <= len(api) <= 400:
        raise ValueError("Unexpected ShaderApi029 slot count")
    output += [method(result.strip(), name, parameters, suffix or "", "moduleAPI")
               for result, name, parameters, suffix in api]
    output += ["};", "", "class ModuleDevice final : public IShaderDevice {", "public:"]
    device = (root / "../../public/shaderapi/IShaderDevice.h").read_text(errors="replace")
    device = device.split("abstract_class IShaderDevice\n", 1)[1].split("\n};", 1)[0]
    device = re.sub(r"//[^\n]*", "", device)
    slots = re.findall(r"virtual\s+([^;{}]+?)\b(\w+)\s*\(([^()]*)\)\s*(const)?\s*=\s*0;", device)
    for result, name, parameters, suffix in slots:
        if name != "DoStartupShaderPreloading":  # ToGL-only ABI slot
            output.append(method(" ".join(result.split()), name, parameters, suffix or "", "moduleDevice"))
    output += ["};", ""]
    Path(sys.argv[1]).write_text("\n".join(output))


if __name__ == "__main__":
    main()
