//===========================================================================//
//
// Purpose: The file defines dictionary names for commonly used strings to reduce
// packet sizes when communicating between clients and servers.
//
// Numbers should never be reused, old ones should be commented out.
//
//=============================================================================

DICTIONARY_NAME( 1, accountid )
DICTIONARY_NAME( 2, password )
DICTIONARY_NAME( 3, cl_use_opens_buy_menu )
DICTIONARY_NAME( 4, tv_nochat )
DICTIONARY_NAME( 5, cl_clanid )
DICTIONARY_NAME( 6, name )
DICTIONARY_NAME( 7, cl_interp_ratio )
DICTIONARY_NAME( 8, cl_predict )
DICTIONARY_NAME( 9, cl_updaterate )
DICTIONARY_NAME( 10, cl_session )
DICTIONARY_NAME( 11, voice_loopback )
DICTIONARY_NAME( 12, cl_lagcompensation )
DICTIONARY_NAME( 13, cl_color )
DICTIONARY_NAME( 14, cl_cmdrate )
DICTIONARY_NAME( 15, net_maxroutable )
DICTIONARY_NAME( 16, rate )
DICTIONARY_NAME( 17, cl_predictweapons )
DICTIONARY_NAME( 18, cl_autohelp )
DICTIONARY_NAME( 19, cl_interp )
DICTIONARY_NAME( 20, cl_autowepswitch )
DICTIONARY_NAME( 21, cl_spec_mode )
DICTIONARY_NAME( 22, tv_relay )
DICTIONARY_NAME( 23, hltv_slots )
DICTIONARY_NAME( 24, hltv_clients )
DICTIONARY_NAME( 25, hltv_addr )
DICTIONARY_NAME( 26, hltv_proxies )
DICTIONARY_NAME( 27, sv_bot_difficulty_kbm )
DICTIONARY_NAME( 28, hltv_sdr )
DICTIONARY_NAME( 29, steamworks_sessionid_client )
DICTIONARY_NAME( 30, sdr_routing )
