//========= Copyright © 1996-2005, Valve Corporation, All rights reserved. ============//
//
// Purpose: Data for Autobuy and Rebuy 
//
//=============================================================================//

#include "cbase.h"
#include "cs_autobuy.h"

// Weapon class information for each weapon including the class name and the buy command alias.
AutoBuyInfoStruct g_autoBuyInfo[] = 
{
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY0, "glock" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY0, "hkp2000" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY0, "usp_silencer" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY1, "elite" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY2, "p250" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY3, "tec9" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY3, "fn57" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_SECONDARY4, "deagle" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE0, "galilar" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE0, "famas" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE1, "ak47" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE1, "m4a1" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE1, "m4a1_silencer" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SNIPERRIFLE),		LOADOUT_POSITION_RIFLE2, "ssg08" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE3, "aug" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_RIFLE),			LOADOUT_POSITION_RIFLE3, "sg556" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SNIPERRIFLE),		LOADOUT_POSITION_RIFLE4, "awp" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SNIPERRIFLE),		LOADOUT_POSITION_RIFLE5, "scar20" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SNIPERRIFLE),		LOADOUT_POSITION_RIFLE5, "g3sg1" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SHOTGUN),			LOADOUT_POSITION_HEAVY0, "nova" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SHOTGUN),			LOADOUT_POSITION_HEAVY1, "xm1014" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SHOTGUN),			LOADOUT_POSITION_HEAVY2, "mag7" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_MACHINEGUN),		LOADOUT_POSITION_HEAVY3, "m249" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_MACHINEGUN),		LOADOUT_POSITION_HEAVY4, "negev" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG0, "mac10" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG0, "mp9" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG1, "mp7" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG2, "ump45" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG3, "p90" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_PRIMARY | AUTOBUYCLASS_SMG),				LOADOUT_POSITION_SMG4, "bizon" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_ARMOR),									LOADOUT_POSITION_EQUIPMENT0, "vest" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_ARMOR),									LOADOUT_POSITION_EQUIPMENT1, "vesthelm" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_SECONDARY | AUTOBUYCLASS_PISTOL),			LOADOUT_POSITION_EQUIPMENT2, "taser" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_DEFUSER),									LOADOUT_POSITION_EQUIPMENT3, "defuser" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_ARMOR),									LOADOUT_POSITION_EQUIPMENT4, "heavyarmor" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE0, "molotov" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE0, "incgrenade" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE1, "decoy" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE2, "flashbang" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE3, "hegrenade" },
	{ (AutoBuyClassType)(AUTOBUYCLASS_GRENADE),									LOADOUT_POSITION_GRENADE4, "smokegrenade" },

	{ (AutoBuyClassType)0, LOADOUT_POSITION_INVALID, "" } // last one, must be at end.
};
