#if !defined CS_PLAYER_RANK_SHARED_H
#define CS_PLAYER_RANK_SHARED_H

enum MedalCategory_t
{
	MEDAL_CATEGORY_NONE = -1, 
	MEDAL_CATEGORY_START = 0,
	MEDAL_CATEGORY_TEAM_AND_OBJECTIVE = MEDAL_CATEGORY_START,
	MEDAL_CATEGORY_COMBAT,
	MEDAL_CATEGORY_WEAPON,
	MEDAL_CATEGORY_MAP,
	MEDAL_CATEGORY_ARSENAL,
	MEDAL_CATEGORY_ACHIEVEMENTS_END,
	MEDAL_CATEGORY_SEASON_COIN = MEDAL_CATEGORY_ACHIEVEMENTS_END,
	MEDAL_CATEGORY_COUNT,
};

#define MEDAL_SEASON_ACCESS_OPERATION_NAME "op08"

enum MedalRank_t
{
	MEDAL_RANK_NONE,
	MEDAL_RANK_BRONZE,
	MEDAL_RANK_SILVER,
	MEDAL_RANK_GOLD,
	MEDAL_RANK_COUNT
};

#endif