//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( dz_blacksite )
// MAPGROUPENUM( xl_dust )
