//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( de_dust2 )

// Group Delta
MAPGROUPENUM( de_mirage )
MAPGROUPENUM( de_inferno )
MAPGROUPENUM( de_cache )
MAPGROUPENUM( de_cbble )

// Group Sigma
MAPGROUPENUM( de_austria ) // out of competitive Jan-2019
MAPGROUPENUM( de_subzero ) // out of competitive Jan-2019
MAPGROUPENUM( de_biome ) // in competitive since 05-Nov-2018
MAPGROUPENUM( de_zoo ) // in competitive since Jan-2019
MAPGROUPENUM( de_abbey ) // in competitive since Jan-2019
MAPGROUPENUM( de_train )
MAPGROUPENUM( de_overpass )
MAPGROUPENUM( de_nuke )
MAPGROUPENUM( de_canals ) // not in competitive

// Hostage Group
MAPGROUPENUM( cs_agency		)
MAPGROUPENUM( cs_office )
MAPGROUPENUM( cs_italy )	 // not in competitive
MAPGROUPENUM( cs_assault )	 // not in competitive
MAPGROUPENUM( cs_militia )	 // not in competitive

