//=========== Copyright Valve Corporation, All rights reserved. ===============//
//
// Purpose: 
//=============================================================================//

#include "cbase.h"

#include "panorama/csgo_panorama.h"
#include "panorama/uischeduleddel.h"
#include "panorama/ui_popup_manager.h"
#include "panorama/ui_root.h"

#include "panorama/ui_canvas.h"

#include "gameui_interface.h"

#include "materialsystem/imaterialsystem.h"
#include "materialsystem/imaterialproxy.h"
#include "materialsystem/imaterialvar.h"
#include "imaterialproxydict.h"
#include "materialsystem/ivisualsdataprocessor.h"
#include "materialsystem/icompositetexture.h"
#include "matsys_controls/matsyscontrols.h"
#include "istudiorender.h"
#include "materialsystem/imaterial.h"
#include "materialsystem/imaterialsystem.h"
#include "materialsystem/imaterialsystemhardwareconfig.h"
#include "tier2/renderutils.h"
#include "materialsystem/imesh.h"
#include "shaderapi/ishaderapi.h"
#include "view_shared.h"
#include "ivrenderview.h"
#include "game/client/irendercaptureconfiguration.h"
#include "viewpostprocess.h"
#include "renderparm.h"

#include "tier1/keyvalues.h"

#include "cs_app_lifetime_gamestats.h"
#include "panorama/source2/ipanoramaui.h"

#include "tier1/callqueue.h"
#include "IGameUIFuncs.h"


// memdbgon must be the last include file in a .cpp file!!!
#include <tier0/memdbgon.h>

REGISTER_PANEL2D_FACTORY( CUI_Canvas, UICanvas );

using namespace panorama;


static ConVar s_convarPanoramaCanvasSSAA( "@panorama_canvas_ssaa", "1", FCVAR_DEVELOPMENTONLY, "0-off, 1-use ssaa if possible, will add (or fallback to) fxaa if scratch rt not large enough for 1.25x supersmapling in both dimensions" );
static ConVar s_convarPanoramaCanvasFXAA( "@panorama_canvas_fxaa", "0", FCVAR_DEVELOPMENTONLY, "0-off, 1-always use fxaa (not just as a fallback if scratch rt not large enough for SSAA)" );
static ConVar s_convarPanoramaCanvasSSAAScale( "@panorama_canvas_ssaa_scale", "2.0", FCVAR_DEVELOPMENTONLY, "Scaling of panel size for ssaa" );
static ConVar s_convarPanoramaCanvasSSAAMinScale( "@panorama_canvas_ssaa_min_scale", "1.5", FCVAR_DEVELOPMENTONLY, "min scaling of panel size for ssaa to be effective, otherwise resorts to fxaa" );

static ConVar s_convarPanoramaCanvasFXAASubpixelQ( "@panorama_canvas_fxaa_subpixel_Q", "0.75", FCVAR_DEVELOPMENTONLY, "Effects sub-pixel AA quality and inversely sharpness (only used on FXAA Quality): (0.0 - off), (1.0 - upper limit, softer), default = 0.75" );
static ConVar s_convarPanoramaCanvasFXAAEdgeThresholdQ( "@panorama_canvas_fxaa_edge_threshold_Q", ".166", FCVAR_DEVELOPMENTONLY, "The minimum amount of local contrast required to apply algorithm: (0.063 - overkill, slower), (0.125 - high quality), (0.166 - default), (0.250 - low quality), (0.333 - too little, faster)" );
static ConVar s_convarPanoramaCanvasFXAAEdgeThresholdMinQ( "@panorama_canvas_fxaa_edge_threshold_min_Q", "0.0", FCVAR_DEVELOPMENTONLY, "Trims the algorithm from processing darks: (0.0312 - visible limit, slower), (0.0625 - high quality, faster), (0.0833 - upper limit, the start of visible unfiltered edges). Special note: when using FXAA_GREEN_AS_LUMA, likely want to set this to zero" );

#define CANVAS_SS_RT_NAME		"_rt_FullFrameFB2"
#define CANVAS_SS_DEPTH_NAME	"_rt_FullFrameDepth"


//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
class CUI_Canvas_DrawCommand
{
public:
	CUI_Canvas_DrawCommand* m_pNext;
	CUI_Canvas_DrawCommand() : m_pNext( nullptr ) {}
	virtual ~CUI_Canvas_DrawCommand() {}
	virtual void Execute( IMatRenderContext* pRenderContext ) = 0;

private:
	CUI_Canvas_DrawCommand( const CUI_Canvas_DrawCommand& );
	CUI_Canvas_DrawCommand& operator=( const CUI_Canvas_DrawCommand& );
};

template <typename T>
class CUI_Canvas_DrawCommandLambda : public CUI_Canvas_DrawCommand
{
public:
	T drawCommand;
	CUI_Canvas_DrawCommandLambda( const T& fn )
		: drawCommand( fn )
	{
	}
	virtual void Execute( IMatRenderContext* pRenderContext )
	{
		drawCommand( pRenderContext );
	}
};

template <typename T>
CUI_Canvas_DrawCommandLambda<T>* MakeDrawCommand( const T& fn )
{
	return new CUI_Canvas_DrawCommandLambda<T>( fn );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
CUI_Canvas::CUI_Canvas( CPanel2D *pParent, const char *pchID )
	: CRenderPanel( pParent, pchID, ePanelFlags_DontFireOnLoad )
	, m_bHasLayoutTraversed( false )
{
	// We must uniqueify the world name
	static int s_nIndex = 1;
	char pAutoGeneratedID[128];
	if ( !pchID || !pchID[0] )
	{
		pchID = "unknown_canvas_panel";
	}

	V_sprintf_safe( pAutoGeneratedID, "%s_%d", pchID, s_nIndex );
	++s_nIndex;
	pchID = pAutoGeneratedID;

	m_pRenderer = NULL;

	RegisterForReadyEvents( true );
	
	if ( !UIEngine()->BHaveEventHandlersRegisteredForType( CUI_Canvas::GetPanelSymbol() ) )
	{
		RegisterEventHandlerOnPanelType( ReadyForDisplay(), &CUI_Canvas::OnReadyForDisplay );
		RegisterEventHandlerOnPanelType( UnreadyForDisplay(), &CUI_Canvas::OnUnreadyForDisplay );
	}

	SetAcceptsFocus( true );
	SetAcceptsInput( true );

 	if ( g_pPanoramaUIEngine )
 	{
 		g_pPanoramaUIEngine->AddDeviceDependentObject( this );
 	}

	Init();
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
CUI_Canvas::~CUI_Canvas()
{
	ClearCommandQueue();

 	if ( g_pPanoramaUIEngine )
 	{
 		g_pPanoramaUIEngine->RemoveDeviceDependentObject( this );
 	}

	if ( m_pRenderer )
		m_pRenderer->Release();

	m_pRenderer = nullptr;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::Init()
{
	m_pRenderer = new CUI_CanvasRenderer();
	SetRenderThreadCallback( m_pRenderer, k_ERenderCallbackFlagsRenderTargetMode );

	m_pCommandQueue = nullptr;
	m_pCommandQueueTail = &m_pCommandQueue;

	m_bClearQueue = false;
	m_bScalingDisabled = false;

//	m_flLastTime = 0.0f;

	m_bAllowDrawing = false;

	m_bDrawing = false;

	m_flLastMouseX = 0.0f;
	m_flLastMouseY = 0.0f;

	SetDrawSize( 10.0f );
	SetDrawColor( Color( 255, 0, 0, 255 ) );

	m_nPanoramaSurfaceWidth = 0;
	m_nPanoramaSurfaceHeight = 0;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::ClearCommandQueue( void )
{
	CUI_Canvas_DrawCommand *pCmd = m_pCommandQueue;
	m_pCommandQueue = nullptr;
	while ( pCmd != nullptr )
	{
		CUI_Canvas_DrawCommand * const pNext = pCmd->m_pNext;
		delete pCmd;
		pCmd = pNext;
	}
	m_pCommandQueueTail = &m_pCommandQueue;
	m_bClearQueue = true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::EnqueueCommand( CUI_Canvas_DrawCommand *pCmd )
{
	if ( m_pRenderer == nullptr )
	{
		delete pCmd;
		return;
	}

	*m_pCommandQueueTail = pCmd;
	m_pCommandQueueTail = &pCmd->m_pNext;
	SetRepaint( EPanelRepaint::k_EPanelRepaintFull );

	m_pRenderer->SetNeedsRedraw( true );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::SetScalingDisabled( bool bDisabled )
{
	m_bScalingDisabled = bDisabled;
	SetRepaint( EPanelRepaint::k_EPanelRepaintFull );
}

//-----------------------------------------------------------------------------
// Canvas Draw commands
//-----------------------------------------------------------------------------
void CUI_Canvas::Clear( const Color &clearColor )
{
	ClearCommandQueue();


	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		pRenderContext->ClearColor4ub( clearColor.r(), clearColor.g(),clearColor.b(), clearColor.a() );
		pRenderContext->ClearBuffers( true, true );
	}
	) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawLine( const Vector2D& v0, const Vector2D& v1, const Color& drawColor )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_LINES, 2 );

		meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v0.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v1.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawLineRect( const Vector2D& v0, const Vector2D& v1, const Color& drawColor )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_LINE_LOOP, 4 );

		unsigned char r = drawColor.r();
		unsigned char g = drawColor.g();
		unsigned char b = drawColor.b();
		unsigned char a = drawColor.a();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v0.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v1.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v1.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v0.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}

#define CANVAS_CIRCLE_POINT_COUNT 24
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawFilledCircle( const Vector2D& vPos, float flRadius, const Color& drawColor )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		int nNumTriangles = CANVAS_CIRCLE_POINT_COUNT;

		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_TRIANGLES, nNumTriangles * 3 );

		float x0 = pRenderer->GetUIScaleX() * vPos.x;
		float y0 = pRenderer->GetUIScaleX() * vPos.y;

		for ( int i = 0; i < nNumTriangles; ++i )
		{
			float x1 = pRenderer->GetUIScaleX() * ( vPos.x + flRadius * cos( i * 2 * M_PI / CANVAS_CIRCLE_POINT_COUNT ) );
			float y1 = pRenderer->GetUIScaleX() * ( vPos.y + flRadius * sin( i * 2 * M_PI / CANVAS_CIRCLE_POINT_COUNT ) );

			float x2 = pRenderer->GetUIScaleX() * ( vPos.x + flRadius * cos( (i+1) * 2 * M_PI / CANVAS_CIRCLE_POINT_COUNT ) );
			float y2 = pRenderer->GetUIScaleX() * ( vPos.y + flRadius * sin( (i+1) * 2 * M_PI / CANVAS_CIRCLE_POINT_COUNT ) );

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x0, y0, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x1, y1, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x2, y2, 0.0f );
			meshBuilder.AdvanceVertex();
		}

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawFilledWedge( const Vector2D& vPos, float flRadius, float flStartAngle, float flAngleDelta, const Color& drawColor )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	Vector2D vPosCopy = vPos;
	Color colorCopy = drawColor;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		int nNumTriangles = CANVAS_CIRCLE_POINT_COUNT;

		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_TRIANGLES, nNumTriangles * 3 );

		float x0 = pRenderer->GetUIScaleX() * vPos.x;
		float y0 = pRenderer->GetUIScaleX() * vPos.y;

		float flAngleIncrement = flAngleDelta / ( nNumTriangles - 1 );
		for ( int i = 0; i < nNumTriangles; ++i )
		{
			float x1 = pRenderer->GetUIScaleX() * ( vPosCopy.x + flRadius * cos( flStartAngle + i * flAngleIncrement ) );;
			float y1 = pRenderer->GetUIScaleY() * ( vPosCopy.y + flRadius * sin( flStartAngle + i * flAngleIncrement ) );

			float x2 = pRenderer->GetUIScaleX() * ( vPosCopy.x + flRadius * cos( flStartAngle + (i+1) * flAngleIncrement ) );;
			float y2 = pRenderer->GetUIScaleY() * ( vPosCopy.y + flRadius * sin( flStartAngle + (i+1) * flAngleIncrement ) );

			meshBuilder.Color4ub( drawColor.r()*0.5, drawColor.g()*0.5, drawColor.b()*0.5, drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x0, y0, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x1, y1, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( x2, y2, 0.0f );
			meshBuilder.AdvanceVertex();
		}

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawLineCircle( const Vector2D& vPos, float flRadius, const Color& drawColor )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		const int nPointCount = CANVAS_CIRCLE_POINT_COUNT;

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_LINE_LOOP, nPointCount + 1 );

		// start
		meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( pRenderer->GetUIScaleX() * ( vPos.x + flRadius ), pRenderer->GetUIScaleX() * vPos.y, 0.0f );
		meshBuilder.AdvanceVertex();

		for ( int i = 1; i < nPointCount; ++i )
		{
			const float flTheta = i * 2 * M_PI / nPointCount;

			meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( pRenderer->GetUIScaleX() * ( vPos.x + flRadius * cos( flTheta ) ), pRenderer->GetUIScaleY() * ( vPos.y + flRadius * sin( flTheta ) ), 0.0f );
			meshBuilder.AdvanceVertex();
		}

		// back to start
		meshBuilder.Color4ub( drawColor.r(), drawColor.g(), drawColor.b(), drawColor.a() );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( pRenderer->GetUIScaleX() * ( vPos.x + flRadius ), pRenderer->GetUIScaleX() * vPos.y, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}
//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
class CUI_Canvas_DrawPolyCommand : public CUI_Canvas_DrawCommand
{
public:
	CUI_CanvasRenderer *m_pRenderer;
	CUtlVector< Vector2D > m_vPoints;
	CUtlVector< Color > m_vColors;

	CUI_Canvas_DrawPolyCommand( CUI_CanvasRenderer *pRenderer, int nNumPoints, const Vector2D *pPoints, const Color *pColors )
	{
		m_pRenderer = pRenderer;
		m_vPoints.AddMultipleToTail( nNumPoints, pPoints );
		m_vColors.AddMultipleToTail( nNumPoints, pColors );
	}

	CUI_Canvas_DrawPolyCommand( CUI_CanvasRenderer *pRenderer, int nNumPoints, const Vector2D *pPoints, const Color &color )
	{
		m_pRenderer = pRenderer;
		m_vPoints.AddMultipleToTail( nNumPoints, pPoints );
		FOR_EACH_VEC( m_vPoints, i )
		{
			m_vColors.AddToTail( color );
		}
	}

	virtual void Execute( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = m_pRenderer->GetUIScaleX();
		const float flUIScaleY = m_pRenderer->GetUIScaleY();

		int nNumTris = m_vPoints.Count() - 2;
		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, m_pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_TRIANGLES, nNumTris * 3 );

		for ( int i = 0; i < nNumTris; i++ )
		{
			meshBuilder.Color4ub( m_vColors[ 0 ].r(), m_vColors[ 0 ].g(), m_vColors[ 0 ].b(), m_vColors[ 0 ].a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( m_vPoints[ 0 ].x * flUIScaleX, m_vPoints[ 0 ].y * flUIScaleY, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( m_vColors[ i+1 ].r(), m_vColors[ i+1 ].g(), m_vColors[ i+1 ].b(), m_vColors[ i+1 ].a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( m_vPoints[ i+1 ].x * flUIScaleX, m_vPoints[ i+1 ].y * flUIScaleY, 0.0f );
			meshBuilder.AdvanceVertex();

			meshBuilder.Color4ub( m_vColors[ i+2 ].r(), m_vColors[ i+2 ].g(), m_vColors[ i+2 ].b(), m_vColors[ i+2 ].a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( m_vPoints[ i+2 ].x * flUIScaleX, m_vPoints[ i+2 ].y * flUIScaleY, 0.0f );
			meshBuilder.AdvanceVertex();
		}

		meshBuilder.End();
		m_pMesh->Draw();
	}
};

void CUI_Canvas::DrawPoly( int nPointCount, const Vector2D *pPoints, const Color *pColors )
{
	EnqueueCommand( new CUI_Canvas_DrawPolyCommand( m_pRenderer, nPointCount, pPoints, pColors ) );
}

void CUI_Canvas::DrawPoly( int nPointCount, const Vector2D *pPoints, const Color &color )
{
	EnqueueCommand( new CUI_Canvas_DrawPolyCommand( m_pRenderer, nPointCount, pPoints, color ) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawThickLine( const Vector2D &v0, const Vector2D &v1, float flThickness, const Color &drawColor )
{
	Vector2D vDir = v1 - v0;
	vDir.NormalizeInPlace();

	const Vector2D vOrthogonal( vDir.y, -vDir.x );
	const Vector2D vHalfThick = flThickness * vOrthogonal * 0.5f;

	Vector2D polyLine[ 4 ] = {
		v0 - vHalfThick,
		v0 + vHalfThick,
		v1 + vHalfThick,
		v1 - vHalfThick
	};
	DrawPoly( V_ARRAYSIZE( polyLine ), polyLine, drawColor );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawThickLinePoints( int nNumPoints, const Vector2D *pPoints, float flThickness, const Color &drawColor )
{
	int nNumThickLines = nNumPoints - 1;

	DrawFilledCircle( pPoints[0], flThickness * 0.5f, drawColor );
	for ( int i = 0; i < nNumThickLines; i++ )
	{
		Vector2D vDir = pPoints[ i + 1 ] - pPoints[ i ];
		vDir.NormalizeInPlace();

		const Vector2D vOrthogonal( vDir.y, -vDir.x );
		const Vector2D vHalfThick = flThickness * vOrthogonal * 0.5f;

		Vector2D polyLine[ 4 ] = {
			pPoints[ i ] - vHalfThick,
			pPoints[ i ] + vHalfThick,
			pPoints[ i + 1 ] + vHalfThick,
			pPoints[ i + 1 ] - vHalfThick
		};
		DrawPoly( V_ARRAYSIZE( polyLine ), polyLine, drawColor );
		DrawFilledCircle( pPoints[ i + 1 ], flThickness * 0.5f, drawColor );
	}

}


//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawRect( const Vector2D& v0, const Vector2D& v1, const Color& drawColor, IMaterial *pMaterial )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_QUADS, 1 );

		unsigned char r = drawColor.r();
		unsigned char g = drawColor.g();
		unsigned char b = drawColor.b();
		unsigned char a = drawColor.a();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
		meshBuilder.Position3f( v0.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 1.0f, 0.0f );
		meshBuilder.Position3f( v1.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 1.0f, 1.0f );
		meshBuilder.Position3f( v1.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, 0.0f, 1.0f );
		meshBuilder.Position3f( v0.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawRect( const Vector2D& v0, const Vector2D& v1, const Vector2D& uv0, const Vector2D& uv1, const Color& drawColor, IMaterial *pMaterial )
{
	CUI_CanvasRenderer *pRenderer = m_pRenderer;
	if ( !pRenderer )
		return;

	EnqueueCommand( MakeDrawCommand(
		[ = ]( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = pRenderer->GetUIScaleX();
		const float flUIScaleY = pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, pMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_QUADS, 1 );

		unsigned char r = drawColor.r();
		unsigned char g = drawColor.g();
		unsigned char b = drawColor.b();
		unsigned char a = drawColor.a();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, uv0.x, uv0.y );
		meshBuilder.Position3f( v0.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, uv1.x, uv0.y );
		meshBuilder.Position3f( v1.x * flUIScaleX, v0.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, uv1.x, uv1.y );
		meshBuilder.Position3f( v1.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.Color4ub( r, g, b, a );
		meshBuilder.TexCoord2f( 0, uv0.x, uv1.y );
		meshBuilder.Position3f( v0.x * flUIScaleX, v1.y * flUIScaleY, 0.0f );
		meshBuilder.AdvanceVertex();

		meshBuilder.End();
		m_pMesh->Draw();
	}
	) );
}


//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
class CUI_Canvas_DrawRectsCommand : public CUI_Canvas_DrawCommand
{
public:
	CUI_CanvasRenderer *m_pRenderer;
	CUtlVector< Vector > m_vPoints;
	CUtlVector< Color > m_vColors;
	CUtlVector< Vector2D > m_vUVs;
	IMaterial *m_pMaterial;

	CUI_Canvas_DrawRectsCommand( CUI_CanvasRenderer *pRenderer, int nNumPoints, const Vector2D *pPoints, const Vector2D *pUVs, const Color *pColors, IMaterial *pMaterial )
	{
		m_pRenderer = pRenderer;
		m_vPoints.EnsureCapacity( nNumPoints );
		const float k_flScaleX = pRenderer->GetUIScaleX();
		const float k_flScaleY = pRenderer->GetUIScaleY();
		for ( int i = 0; i < nNumPoints; ++i )
		{
			m_vPoints.AddToTail( Vector( pPoints[ i ].x * k_flScaleX, pPoints[ i ].y * k_flScaleY, 0.0f ) );
		}
		m_vColors.AddMultipleToTail( nNumPoints, pColors );
		m_vUVs.AddMultipleToTail( nNumPoints, pUVs );
		m_pMaterial = pMaterial;
	}

	virtual void Execute( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = m_pRenderer->GetUIScaleX();
		const float flUIScaleY = m_pRenderer->GetUIScaleY();

		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, m_pMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_QUADS, m_vPoints.Count()/4 );

		for ( int i = 0; i < m_vPoints.Count(); i++ )
		{
			meshBuilder.Color4ub( m_vColors[ i ].r(), m_vColors[ i ].g(), m_vColors[ i ].b(), m_vColors[ i ].a() );
			meshBuilder.TexCoord2f( 0, m_vUVs[ i ].x, m_vUVs[ i ].y );
			meshBuilder.Position3f( m_vPoints[ i ].x, m_vPoints[ i ].y, 0.0f );
			meshBuilder.AdvanceVertex();
		}

		meshBuilder.End();
		m_pMesh->Draw();
	}
};

void CUI_Canvas::DrawRects( int nPointCount, const Vector2D *pPoints, const Vector2D *pUVs, const Color* pColors, IMaterial *pMaterial )
{
	EnqueueCommand( new CUI_Canvas_DrawRectsCommand( m_pRenderer, nPointCount, pPoints, pUVs, pColors, pMaterial ) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
class CUI_Canvas_DrawLinePointsCommand : public CUI_Canvas_DrawCommand
{
public:
	CUI_CanvasRenderer *m_pRenderer;
	CUtlVector< Vector2D > m_vPoints;
	Color m_Color;

	CUI_Canvas_DrawLinePointsCommand( CUI_CanvasRenderer *pRenderer, int nNumPoints, const Vector2D *pPoints, const Color &color )
	{
		m_pRenderer = pRenderer;
		m_vPoints.AddMultipleToTail( nNumPoints, pPoints );
		m_Color = color;
	}

	virtual void Execute( IMatRenderContext *pRenderContext )
	{
		const float flUIScaleX = m_pRenderer->GetUIScaleX();
		const float flUIScaleY = m_pRenderer->GetUIScaleY();

		int nLines = m_vPoints.Count() - 1;
		IMesh* m_pMesh = pRenderContext->GetDynamicMesh( true, NULL, NULL, m_pRenderer->m_WhiteMaterial );
		CMeshBuilder meshBuilder;
		meshBuilder.Begin( m_pMesh, MATERIAL_LINE_STRIP, nLines );

		for ( int i = 0; i < nLines; i++ )
		{
			meshBuilder.Color4ub( m_Color.r(), m_Color.g(), m_Color.b(), m_Color.a() );
			meshBuilder.TexCoord2f( 0, 0.0f, 0.0f );
			meshBuilder.Position3f( m_vPoints[ i ].x * flUIScaleX, m_vPoints[ i ].y * flUIScaleY, 0.0f );
			meshBuilder.AdvanceVertex();
		}

		meshBuilder.End();
		m_pMesh->Draw();
	}
};

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_Canvas::DrawLinePoints( int nPointCount, const Vector2D *pPoints, const Color &color )
{
	EnqueueCommand( new CUI_Canvas_DrawLinePointsCommand( m_pRenderer, nPointCount, pPoints, color ) );
}

//-----------------------------------------------------------------------------
// Purpose: Setup JS object template
//-----------------------------------------------------------------------------
void CUI_Canvas::SetupJavascriptObjectTemplate()
{
	BaseClass::SetupJavascriptObjectTemplate();

	RegisterJSMethod( "SetDrawColorJS", PANORAMA_DELEGATE( &CUI_Canvas::SetDrawColorJS ) );
	RegisterJSMethod( "SetDrawSizeJS", PANORAMA_DELEGATE( &CUI_Canvas::SetDrawSizeJS ) );
	RegisterJSMethod( "ClearJS", PANORAMA_DELEGATE( &CUI_Canvas::ClearJS ) );
	RegisterJSMethod( "DrawLinePointsJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawLinePointsJS ) );
	RegisterJSMethod( "DrawPolyJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawPolyJS ) );
	RegisterJSMethod( "DrawShadedPolyJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawShadedPolyJS ) );
	RegisterJSMethod( "DrawLineCircleJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawLineCircleJS ) );
	RegisterJSMethod( "DrawFilledCircleJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawFilledCircleJS ) );
	RegisterJSMethod( "DrawFilledWedgeJS", PANORAMA_DELEGATE( &CUI_Canvas::DrawFilledWedgeJS ) );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::ClearJS( const char *szColor )
{
	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff ); 

	Clear( col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::SetDrawColorJS( const char *szColor )
{
	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	SetDrawColor( col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::SetDrawSizeJS( const float flDrawSize )
{
	SetDrawSize( flDrawSize );
	return true;
}

//-----------------------------------------------------------------------------
// JS array helpers
//-----------------------------------------------------------------------------
static bool Helper_JSArrayToVector2Ds( int nPointCount, v8::Local<v8::Array> points, CUtlVector< Vector2D > &vPoints )
{
	if ( points->Length() % 2 )
		return false;

	Vector2D vP;

	vPoints.EnsureCapacity( nPointCount );

	for ( int i = 0; i < points->Length(); )
	{
		if ( !( points->Get( i )->IsNumber() && points->Get( i + 1 )->IsNumber() ) )
			return false;

		vP.x = (float)points->Get( i )->ToNumber()->Value();
		vP.y = (float)points->Get( i + 1 )->ToNumber()->Value();

		vPoints.AddToTail( vP );

		i += 2;
	}

	return true;
}

static bool Helper_JSArrayToColors( int nPointCount, v8::Local<v8::Array> colors, CUtlVector< Color > &vColors )
{
	Color col;

	vColors.EnsureCapacity( nPointCount );

	for ( int i = 0; i < colors->Length(); i++ )
	{
		if ( !colors->Get( i )->IsString() )
			return false;

		v8::String::Utf8Value szColor( colors->Get( i ) );

		if ( !CSSHelpers::BParseColor( &col, *szColor ) )
			col.SetColor( 0xff, 0xff, 0xff, 0xff );

		vColors.AddToTail( col );
	}
	
	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawLinePointsJS( int nPointCount, v8::Local<v8::Array> points, float flThickness, const char *szColor )
{
	CUtlVector< Vector2D > vPoints;
	
	if ( !Helper_JSArrayToVector2Ds( nPointCount, points, vPoints ) )
		return true;

	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	if ( flThickness <= 1.0f )
	{
		DrawLinePoints( nPointCount, vPoints.Base(), col );
	}
	else
	{
		DrawThickLinePoints( nPointCount, vPoints.Base(), flThickness, col );
	}

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawShadedPolyJS( int nPointCount, v8::Local<v8::Array> points, v8::Local<v8::Array> colors )
{
	CUtlVector< Vector2D > vPoints;

	if ( !Helper_JSArrayToVector2Ds( nPointCount, points, vPoints ) )
		return true;

	CUtlVector< Color > vColors;

	Helper_JSArrayToColors( nPointCount, colors, vColors );

	DrawPoly( nPointCount, vPoints.Base(), vColors.Base() );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawPolyJS( int nPointCount, v8::Local<v8::Array> points, const char *szColor )
{
	CUtlVector< Vector2D > vPoints;

	if ( !Helper_JSArrayToVector2Ds( nPointCount, points, vPoints ) )
		return true;

	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	DrawPoly( nPointCount, vPoints.Base(), col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawLineCircleJS( float flcX, float flcY, float flRadius, const char *szColor )
{
	Vector2D vCentre = Vector2D( flcX, flcY );

	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	DrawLineCircle( vCentre, flRadius, col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawFilledCircleJS( float flcX, float flcY, float flRadius, const char *szColor )
{
	Vector2D vCentre = Vector2D( flcX, flcY );

	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	DrawFilledCircle( vCentre, flRadius, col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::DrawFilledWedgeJS( float flcX, float flcY, float flRadius, float flStartAngle, float flAngleDelta, const char *szColor )
{
	Vector2D vCentre = Vector2D( flcX, flcY );

	Color col;

	if ( !CSSHelpers::BParseColor( &col, szColor ) )
		col.SetColor( 0xff, 0xff, 0xff, 0xff );

	DrawFilledWedge( vCentre, flRadius, flStartAngle, flAngleDelta, col );

	return true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::BSetProperties( const CUtlVector< ParsedPanelProperty_t > &vecProperties )
{
	static CPanoramaSymbol k_symAllowDrawing( "allowDrawing" );

	FOR_EACH_VEC( vecProperties, i )
	{
		const ParsedPanelProperty_t &prop = vecProperties[ i ];
		if ( prop.m_symName == k_symAllowDrawing )
		{
			CSSHelpers::BParseTrueFalse( prop.m_pchValue, &m_bAllowDrawing );
		}
	}

	return true;
}

//-----------------------------------------------------------------------------
// Tell the world renderer it will need to set up its world since it's being painted
//-----------------------------------------------------------------------------
void CUI_Canvas::Paint()
{
	VPROF_BUDGET_THREAD( "CUI_Canvas::Paint", VPROF_BUDGETGROUP_TENFOOT );

	int nW, nH;
	nW = (int)UIPanel()->GetActualRenderWidth();
	nH = (int)UIPanel()->GetActualRenderHeight();
	
	if ( !m_pPanelRT || ( nW != m_pPanelRT->GetTextureWidth() ) || ( nH != m_pPanelRT->GetTextureHeight() ) )
	{
		m_pPanelRT.SafeRelease();
		AccessRenderDevice()->BCreateRenderTargetTexture( &m_pPanelRT, nW, nH );

		if ( m_pRenderer )
			m_pRenderer->SetNeedsRedraw( true );
	}

	BaseClass::Paint();

	if ( !m_pRenderer )
		return;

	if ( !m_pRenderer->NeedsRedraw() )
 		return;

	if ( m_bClearQueue )
	{
		m_bClearQueue = false;
		m_pRenderer->ClearDrawCommands();
	}

	if ( m_pCommandQueue != nullptr )
	{
		*m_pRenderer->m_pDrawCommandsTail = m_pCommandQueue;
		m_pRenderer->m_pDrawCommandsTail = m_pCommandQueueTail;
		m_pCommandQueue = nullptr;
		m_pCommandQueueTail = &m_pCommandQueue;
	}

	if ( m_bScalingDisabled )
	{
		m_pRenderer->m_flUIScaleX = 1.0f;
		m_pRenderer->m_flUIScaleY = 1.0f;
	}
	else
	{
		m_pRenderer->m_flUIScaleX = GetActualUIScaleX();
		m_pRenderer->m_flUIScaleY = GetActualUIScaleY();
	}


	// update scene
//	m_pRenderer->OnTick();
//	float dt = flTime - m_flLastTime;

	CMatRenderContextPtr pRenderContext( g_pMaterialSystem );
	ICallQueue* pCQ = pRenderContext->GetCallQueue();
	if ( pCQ )
	{
		// Queuing a functor to be executed on the render thread. The functor will hold
		// a CRefPtr< IUITexture > and therefore when the functor is destroyed it will 
		// call the CRefPtr destructor that will eventually decrement the ref count.
		// Note that copying a CRefPtr will not automatically increment the ref count
		// so we are incrementing it here
		m_pPanelRT->AddRef();
		pCQ->QueueCall( AccessRenderDevice(), &IUIRenderDevice::PushPanelRT, m_pPanelRT );
	}
	else
	{
		AccessRenderDevice()->PushPanelRT( m_pPanelRT );
	}

	Vector4D scissor( 0, 0, nW, nH );
	m_pRenderer->RenderThreadCallback( &scissor, 0, 0, nW, nH, true );

	if ( pCQ )
	{
		// cf comment above about ref count
		m_pPanelRT->AddRef();
		pCQ->QueueCall( AccessRenderDevice(), &IUIRenderDevice::PopPanelRT, m_pPanelRT );
	}
	else
	{
		AccessRenderDevice()->PopPanelRT( m_pPanelRT  );
	}

//	m_flLastTime = flTime;
}


void CUI_Canvas::OnVisibilityChanged()
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );

	BaseClass::OnVisibilityChanged();
}

//-----------------------------------------------------------------------------
// 
//-----------------------------------------------------------------------------
void CUI_Canvas::SetAntialias( bool bAntialias )
{
	if ( !m_pRenderer )
		return;

	UIPanel()->SetNeedsIntermediateTexture( bAntialias );
	SetRepaint( EPanelRepaint::k_EPanelRepaintFull );
}

//-----------------------------------------------------------------------------
// 
//-----------------------------------------------------------------------------
bool CUI_Canvas::OnGamePadDown( const panorama::GamePadData_t &code )
{
	return false;
}

//-----------------------------------------------------------------------------
// 
//-----------------------------------------------------------------------------
bool CUI_Canvas::OnKeyTyped( const panorama::KeyData_t &unichar )
{
	if ( unichar.m_UniChar == L' ' )
	{
 	}

	return false;
}

bool CUI_Canvas::OnKeyDown( const panorama::KeyData_t &unichar )
{
	// testing
/*	Clear( Color( 128, 128, 128, 255 ) );
	DrawThickLine( Vector2D( 10, 800 ), Vector2D( 800, 10 ), 3.0, Color( 0, 255, 0, 255 ) );

	DrawThickLine( Vector2D( 40, 10 ), Vector2D( 760, 800 ), 10.0, Color( 0, 0, 255, 255 ) );

	Vector2D alinePoly[ 10 ] = { {10,15},{ 60,135 },{ 110,50 },{ 160,285 },{ 210,325 },
								 { 260,300 },{ 310,335 },{ 360,350 },{ 410,375 },{ 460,400 } };

	DrawThickLinePoly(10, alinePoly, 15.0, Color(255,0,0,255) );*/

	return BaseClass::OnKeyDown( unichar );
}

bool CUI_Canvas::OnKeyUp( const panorama::KeyData_t &unichar )
{
	// testing
/*	Clear( Color( 64, 64, 64, 255 ) );
	DrawLine( Vector2D( 10, 10 ), Vector2D( 800, 800 ), Color( 255, 255, 255, 255 ) );
	DrawLine( Vector2D( 10, 800 ), Vector2D( 800, 10 ), Color( 0, 255, 0, 255 ) );

	DrawLineRect( Vector2D( 150, 700 ), Vector2D( 220, 600 ), Color( 255, 0, 255, 255 ) );
	DrawLineRect( Vector2D( 170, 650 ), Vector2D( 260, 550 ), Color( 255, 128, 255, 255 ) );

	DrawLineCircle( Vector2D(300, 400), 150.0, Color(255,255,0,255) );
	DrawFilledCircle( Vector2D( 500, 300 ), 120.0, Color( 0, 255, 255, 255 ) );

	DrawFilledWedge( Vector2D( 600, 650 ), 100.0, M_PI*0.25, M_PI*0.55, Color( 255, 128, 0, 255 ) );
	DrawFilledWedge( Vector2D( 720, 620 ), 75.0, M_PI*0.75, M_PI*1.2, Color( 255, 0, 0, 255 ) );*/

	return BaseClass::OnKeyUp( unichar );
}

bool CUI_Canvas::OnMouseButtonDown( const panorama::MouseData_t &code )
{
	if ( m_bAllowDrawing && ( code.m_MouseCode == panorama::MOUSE_LEFT ) )
		m_bDrawing = true;

	return BaseClass::OnMouseButtonDown( code );
}

bool CUI_Canvas::OnMouseButtonUp( const panorama::MouseData_t &code )
{
	if ( code.m_MouseCode == panorama::MOUSE_LEFT )
		m_bDrawing = false;

	return BaseClass::OnMouseButtonUp( code );
}

bool CUI_Canvas::OnMouseWheel( const panorama::MouseData_t &code )
{
	return BaseClass::OnMouseWheel( code );
}

void CUI_Canvas::OnMouseMove( float flMouseX, float flMouseY )
{
	float flX, flY;

	// match scaling/space of drawing fn coords
	if ( m_bScalingDisabled )
	{
		flX = flMouseX;
		flY = flMouseY;
	}
	else
	{
		// DrawThickLinePoly scales( if enabled ) by GetActualUIScale, so apply inverse here
		flX = flMouseX / GetActualUIScaleX();
		flY = flMouseY / GetActualUIScaleY();
	}

	if ( m_bDrawing )
	{
		Vector2D aLinePoly[ 2 ];

		aLinePoly[ 0 ] = Vector2D( m_flLastMouseX, m_flLastMouseY );
		aLinePoly[ 1 ] = Vector2D( flX, flY );

		DrawThickLinePoints( 2, aLinePoly, m_flDrawSize, m_drawColor );
	}

	m_flLastMouseX = flX;
 	m_flLastMouseY = flY;


	return BaseClass::OnMouseMove( flMouseX, flMouseY );
}

bool CUI_Canvas::OnReadyForDisplay( const panorama::CPanelPtr< panorama::IUIPanel > &pPanel )
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );

	return true;
}

bool CUI_Canvas::OnUnreadyForDisplay( const panorama::CPanelPtr< panorama::IUIPanel > &pPanel )
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );

	// Not displaying the panel anymore, release the panel render target. It will
	// be recreated at the next Paint.
	m_pPanelRT.SafeRelease();

	return true;
}

//-----------------------------------------------------------------------------
//
// IShaderDeviceDependentObject methods
//
//-----------------------------------------------------------------------------
void CUI_Canvas::DeviceLost( void )
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );
}

void CUI_Canvas::DeviceReset( void *pDevice, void *pPresentParameters, void *pHWnd )
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );
}

void CUI_Canvas::ScreenSizeChanged( int width, int height )
{
	if ( m_pRenderer )
		m_pRenderer->SetNeedsRedraw( true );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
bool CUI_Canvas::EnableRendering( bool bEnable )
{
	if ( !m_pRenderer )
		return false;

	if ( bEnable != m_pRenderer->IsRenderingEnabled() )
	{
		m_pRenderer->EnableRendering( bEnable );
	}

	return true;
}

//-----------------------------------------------------------------------------
//
//-----------------------------------------------------------------------------
void CUI_Canvas::SetOnCanvasFirstLayoutEvent( panorama::IUIEvent *pEvent )
{
	static const CPanoramaSymbol k_symPropertyOnCanvasFirstLayout( "oncanvasfirstlayout" );
	UIPanel()->SetPanelEvent( k_symPropertyOnCanvasFirstLayout, pEvent );
}

void CUI_Canvas::ClearOnCanvasFirstLayoutEvent()
{
	static const CPanoramaSymbol k_symPropertyOnCanvasFirstLayout( "oncanvasfirstlayout" );
	m_pIUIPanel->ClearPanelEvents( k_symPropertyOnCanvasFirstLayout );
}

void CUI_Canvas::SetOnCanvasLayoutEvent( panorama::IUIEvent *pEvent )
{
	static const CPanoramaSymbol k_symPropertyOnCanvasLayout( "oncanvaslayout" );
	UIPanel()->SetPanelEvent( k_symPropertyOnCanvasLayout, pEvent );
}

void CUI_Canvas::ClearOnCanvasLayoutEvent()
{
	static const CPanoramaSymbol k_symPropertyOnCanvasLayout( "oncanvaslayout" );
	m_pIUIPanel->ClearPanelEvents( k_symPropertyOnCanvasLayout );
}

void CUI_Canvas::OnLayoutTraverse( float flFinalWidth, float flFinalHeight )
{
	BaseClass::OnLayoutTraverse( flFinalWidth, flFinalHeight );

	if ( flFinalWidth > 0 && flFinalHeight > 0 )
	{
		if ( !m_bHasLayoutTraversed )
		{
			static const CPanoramaSymbol k_symPropertyOnCanvasFirstLayout( "oncanvasfirstlayout" );
			DispatchPanelEvent( k_symPropertyOnCanvasFirstLayout );
			m_bHasLayoutTraversed = true;
		}
		else
		{
			static const CPanoramaSymbol k_symPropertyOnCanvasLayout( "oncanvaslayout" );
			DispatchPanelEvent( k_symPropertyOnCanvasLayout );
		}
	}
}

//-----------------------------------------------------------------------------
// Canvas Renderer
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Helpers
//-----------------------------------------------------------------------------

static float UI_GetAutoPlayTime( void )
{
	static int s_prevTicks = 0;
	static float s_time = 0.0f;

	int ticks = Plat_MSTime();

	// limit delta so that float time doesn't overflow
	if ( s_prevTicks == 0 )
	{
		s_prevTicks = ticks;
	}

	s_time += ( ticks - s_prevTicks ) / 1000.0f;
	s_prevTicks = ticks;

	return s_time;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
CUI_CanvasRenderer::CUI_CanvasRenderer( void )
{
	m_flUIScaleX = 1.0f;
	m_flUIScaleY = 1.0f;

	m_pDrawCommands = nullptr;
	m_pDrawCommandsTail = &m_pDrawCommands;

	m_bRenderWithAA = true;
	m_bForceFXAA = false;

	m_bNeedsRedraw = true;
	m_bEnableRendering = true;

	m_bInPaintMode = false;

	m_flAutoPlayTimeBase = UI_GetAutoPlayTime();

	m_RenderCaptureCamera.Init( Vector( 0, 0, 0 ), QAngle( 0, 0, 0 ), 3.0f, 16384.0f * 1.73205080757f, 30.0f, 1.0f );

	// Super sampling
	m_FullScreenBufferMaterial.Shutdown();
	m_FullScreenBuffer.Shutdown();

	// Set up a material for final SSAA 'resolve' to panorama panel RT
	char pTemp[ 512 ];
	KeyValues *pVMTKeyValuesSSAA = new KeyValues( "PanoramaSSAAResolve" );
	pVMTKeyValuesSSAA->SetString( "$basetexture", CANVAS_SS_RT_NAME );
	Q_snprintf( pTemp, sizeof( pTemp ), "UI_CANVAS_FullScreen_%s", CANVAS_SS_RT_NAME );
	m_FullScreenBufferMaterial.Init( pTemp, TEXTURE_GROUP_OTHER, pVMTKeyValuesSSAA );

	m_FullScreenBufferMaterial->RefreshPreservingMaterialVars();

	// FXAA
	m_FXAAMaterial.Shutdown();

	// Set up material for FXAA 'resolve' to panorama panel RT, if SSAA is enabled at the same time, use this material to perform both
	KeyValues *pVMTKeyValuesFXAA = new KeyValues( "engine_post" );
	pVMTKeyValuesFXAA->SetString( "$basetexture", "_rt_SmallFB0" ); // for bloom, not used here
	pVMTKeyValuesFXAA->SetString( "$fbtexture", CANVAS_SS_RT_NAME );
	pVMTKeyValuesFXAA->SetString( "$BloomEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$AllowVignette", "0" );
	pVMTKeyValuesFXAA->SetString( "$VignetteEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$BlurredVignetteEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$AllowNoise", "0" );
	pVMTKeyValuesFXAA->SetString( "$NoiseEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$VomitEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$Fade", "0" );
	pVMTKeyValuesFXAA->SetString( "$DesaturateEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$AllowLocalContrast", "0" );
	pVMTKeyValuesFXAA->SetString( "$LocalContrastEnable", "0" );
	pVMTKeyValuesFXAA->SetString( "$AAEnable", "1" );
	pVMTKeyValuesFXAA->SetString( "$additive", "0" );
	pVMTKeyValuesFXAA->SetString( "$ignorez", "1" );
	pVMTKeyValuesFXAA->SetString( "$toolmode", "0" );
	pVMTKeyValuesFXAA->SetString( "$panorama", "1" );
	Q_snprintf( pTemp, sizeof( pTemp ), "UI_CANVAS_fxaa" );
	m_FXAAMaterial.Init( pTemp, TEXTURE_GROUP_OTHER, pVMTKeyValuesFXAA );
	m_FXAAMaterial->RefreshPreservingMaterialVars();

	m_bInAARendering = false;
	m_bForceFXAA = false;

	// white
	m_WhiteMaterial.Shutdown();
	m_WhiteMaterial.Init( "vgui/white", TEXTURE_GROUP_OTHER );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
CUI_CanvasRenderer::~CUI_CanvasRenderer()
{
	ClearDrawCommands();
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::ClearDrawCommands( void )
{
	CUI_Canvas_DrawCommand *pCmd = m_pDrawCommands;
	m_pDrawCommands = nullptr;
	while ( pCmd != nullptr )
	{
		CUI_Canvas_DrawCommand * const pNext = pCmd->m_pNext;
		delete pCmd;
		pCmd = pNext;
	}
	m_pDrawCommandsTail = &m_pDrawCommands;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::RenderThreadCallback( Vector4D *pScissorAttribute, float x0, float y0, float x1, float y1, bool bEnableAA )
{
	VPROF_BUDGET_THREAD( "CUI_CanvasRenderer::RenderThreadCallback", VPROF_BUDGETGROUP_TENFOOT );

	if ( !IsRenderingEnabled() )
		return;

	CMatRenderContextPtr pRenderContext( materials );

	if ( ( !g_pMaterialSystemHardwareConfig->IsAAEnabled() ) && ( bEnableAA == false ) )
		bEnableAA = true;

	if ( gameuifuncs->IsPanoramaInECOMode() )
		bEnableAA = false;

	SetRenderWithAA( bEnableAA && ( s_convarPanoramaCanvasSSAA.GetBool() || s_convarPanoramaCanvasFXAA.GetBool() ) );

	BeginPaint( (int)x0, (int)y0, int( x1 ), int( y1 ), pScissorAttribute );

	OnPaint();

	EndPaint( true );

	SetNeedsRedraw( false );
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::BeginAARendering()
{
	m_bInAARendering = false;

	if ( !m_bRenderWithAA ) 
		return;

	// For super sampling use the off-screen render target the material system allocates
	// NOTE: We have to grab it here, as opposed to during init,
	// because the mode hasn't been set by now.
	if ( !m_FullScreenBuffer )
	{
		m_FullScreenBuffer.Init( materials->FindTexture( CANVAS_SS_RT_NAME, "render targets" ) );
	}

	m_bForceFXAA = false;

	// see if we have enough extra resolution to make super sampling worthwhile (from 1.25x up to 2x)
	if ( s_convarPanoramaCanvasSSAA.GetBool() )
	{
		int nMaxSSWidth = m_FullScreenBuffer->GetActualWidth();
		int nMaxSSHeight = m_FullScreenBuffer->GetActualHeight();

		// is SSAA worthwhile for this panel size?
		int nMinSSWidth = (int)( (float)m_nRenderWidth * s_convarPanoramaCanvasSSAAMinScale.GetFloat() );
		int nMinSSHeight = (int)( (float)m_nRenderHeight * s_convarPanoramaCanvasSSAAMinScale.GetFloat() );

		if ( ( nMinSSWidth > nMaxSSWidth ) || ( nMinSSHeight > nMaxSSHeight ) )
		{
			// add fxaa if RT not large enough for SSAA
			m_bForceFXAA = true;
		}
		else
		{
			// clamp ssaa resolution
			m_nRenderWidth = MIN( s_convarPanoramaCanvasSSAAScale.GetFloat() * m_nRenderWidth, nMaxSSWidth );
			m_nRenderHeight = MIN( s_convarPanoramaCanvasSSAAScale.GetFloat() * m_nRenderHeight, nMaxSSHeight );
		}
	}

	CMatRenderContextPtr pRenderContext( materials );

	pRenderContext->PushRenderTargetAndViewport( m_FullScreenBuffer,
												 0, 0, m_nRenderWidth, m_nRenderHeight );
	pRenderContext->PushScissorRect( 0, 0, m_nRenderWidth, m_nRenderHeight );

	pRenderContext->ClearBuffers( true, true, true );

	m_bInAARendering = true;
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::EndAARendering()
{
	if ( !m_bRenderWithAA )
		return;

	if ( !m_bInAARendering )
		return;

	CMatRenderContextPtr pRenderContext( materials );

	pRenderContext->Flush();

	// reset for rendering SS RT back into panel RT
	pRenderContext->PopRenderTargetAndViewport();
	pRenderContext->PopScissorRect();

	int nSSWidth = m_FullScreenBuffer->GetActualWidth();
	int nSSHeight = m_FullScreenBuffer->GetActualHeight();

	float fSSU = (float)( m_nRenderWidth - 1 );
	float fSSV = (float)( m_nRenderHeight - 1 );

	m_nRenderWidth = m_n3DRight - m_n3DLeft;
	m_nRenderHeight = m_n3DBottom - m_n3DTop;

	pRenderContext->PushScissorRect( m_vecScissorAttribute.x, m_vecScissorAttribute.y, m_vecScissorAttribute.x + m_vecScissorAttribute.z, m_vecScissorAttribute.y + m_vecScissorAttribute.w );
	pRenderContext->Viewport( m_n3DLeft, m_n3DTop,
							  m_nRenderWidth, m_nRenderHeight );

	if ( s_convarPanoramaCanvasFXAA.GetBool() || m_bForceFXAA )
	{
		bool bFoundVar = false;
		IMaterialVar *pMaterialParam_FXAAValuesQ = m_FXAAMaterial->FindVar( "$FXAAInternalQ", &bFoundVar, false );
		IMaterialVar *pMaterialParam_FXAAValues1 = m_FXAAMaterial->FindVar( "$AAInternal1", &bFoundVar, false );
		IMaterialVar *pMaterialParam_FXAAValues2 = m_FXAAMaterial->FindVar( "$AAInternal2", &bFoundVar, false );


		float vFXAAValues[ 4 ];
		vFXAAValues[ 0 ] = s_convarPanoramaCanvasFXAASubpixelQ.GetFloat();
		vFXAAValues[ 1 ] = 0.0f; // unused
		vFXAAValues[ 2 ] = s_convarPanoramaCanvasFXAAEdgeThresholdQ.GetFloat();
		vFXAAValues[ 3 ] = s_convarPanoramaCanvasFXAAEdgeThresholdMinQ.GetFloat(); // unused?

		if ( pMaterialParam_FXAAValuesQ )
			pMaterialParam_FXAAValuesQ->SetVecValue( vFXAAValues, 4 );

		float vFXAAValues1[ 4 ] = { 1.0f, 0.0f, 0.0f, 0.0f };
		if ( pMaterialParam_FXAAValues1 )
			pMaterialParam_FXAAValues1->SetVecValue( vFXAAValues1, 4 );

		float vFXAAValues2[ 4 ] = { 0.0f, 0.0f, (float)m_nRenderWidth / (float)nSSWidth, (float)m_nRenderHeight / (float)nSSHeight };
		if ( pMaterialParam_FXAAValues2 )
			pMaterialParam_FXAAValues2->SetVecValue( vFXAAValues2, 4 );

		pRenderContext->EnableColorCorrection( false );

		pRenderContext->DrawScreenSpaceRectangle( m_FXAAMaterial,
												  0, 0, m_nRenderWidth, m_nRenderHeight,
												  0.0f, 0.0f, fSSU, fSSV,
												  m_nRenderWidth, m_nRenderHeight, NULL );
	}
	else
	{
		pRenderContext->DrawScreenSpaceRectangle( m_FullScreenBufferMaterial,
												  0, 0, m_nRenderWidth, m_nRenderHeight,
												  0.0f, 0.0f, fSSU, fSSV,
												  nSSWidth, nSSHeight, NULL );
	}

	m_bInAARendering = false;
}

//-----------------------------------------------------------------------------
// Begins, ends painting from within a panel paint() method
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::BeginPaint( int iLeft, int iTop, int iRight, int iBottom, Vector4D *pScissorAttribute )
{
	Assert( iRight > iLeft );
	Assert( iBottom > iTop );

	// clamp the viewport rectangle to itself while also making sure it is positive
	// e.g. We don't want to change the max coordinate so if nLeft is < 0 we reduce width instead of increasing nRight (i.e. keeping width constant)
	m_n3DLeft = iLeft;
	m_n3DRight = iRight;
	m_n3DLeft = Max( 0, m_n3DLeft );
	m_n3DRight = Max( m_n3DLeft, m_n3DRight );

	m_n3DTop = iTop;
	m_n3DBottom = iBottom;
	m_n3DTop = Max( 0, m_n3DTop );
	m_n3DBottom = Max( m_n3DTop, m_n3DBottom );

	m_nRenderWidth = m_n3DRight - m_n3DLeft;
	m_nRenderHeight = m_n3DBottom - m_n3DTop;

	// clip space extents of panel
	m_flClipLeft = -1.0f;
	m_flClipRight = 1.0f;
	m_flClipBottom = -1.0f;
	m_flClipTop = 1.0f;

	if ( m_n3DLeft == 0 )
	{
		float flRatio = -(float)iLeft / (float)( iRight - iLeft );
		m_flClipLeft = m_flClipLeft + ( flRatio *  ( m_flClipRight - m_flClipLeft ) );
	}

	if ( m_n3DTop == 0 )
	{
		float flRatio = -(float)iTop / (float)( iBottom - iTop );
		m_flClipTop = m_flClipBottom + ( ( 1.0 - flRatio ) * ( m_flClipTop - m_flClipBottom ) );
	}

//	m_flAspect = (float)( iRight - iLeft ) / (float)( iBottom - iTop );
//	SetCameraAspect( m_flAspect );

	Assert( !m_bInPaintMode );
	m_bInPaintMode = true;

	CMatRenderContextPtr pRenderContext( materials );

	BeginAARendering();

	if ( !m_bInAARendering )
	{
		pRenderContext->PushScissorRect( pScissorAttribute->x, pScissorAttribute->y, pScissorAttribute->x + pScissorAttribute->z, pScissorAttribute->y + pScissorAttribute->w );
		pRenderContext->Viewport( m_n3DLeft, m_n3DTop,
								  m_nRenderWidth, m_nRenderHeight );
	}
	else
	{
		m_vecScissorAttribute = *pScissorAttribute;
	}

	pRenderContext->CullMode( MATERIAL_CULLMODE_CCW );

	// Don't draw the 3D scene w/ stencil
	ShaderStencilState_t state;
	state.m_bEnable = false;
	pRenderContext->SetStencilState( state );

	// matrices
	pRenderContext->MatrixMode( MATERIAL_PROJECTION );
	pRenderContext->PushMatrix();
	pRenderContext->LoadIdentity();
	pRenderContext->Scale( 1, -1, 1 );
	pRenderContext->Ortho( 0, 0, m_nRenderWidth, m_nRenderHeight, -1.0f, 1.0f );

	pRenderContext->MatrixMode( MATERIAL_MODEL );
	pRenderContext->LoadIdentity();

	pRenderContext->MatrixMode( MATERIAL_VIEW );
	pRenderContext->LoadIdentity();
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::EndPaint( bool bIgnoreAlphaWhenCompositing )
{
	// Can't use this feature when drawing into the 3D world
	Assert( m_bInPaintMode );
	m_bInPaintMode = false;

	CMatRenderContextPtr pRenderContext( materials );

	EndAARendering();

	pRenderContext->PopScissorRect();
}

//-----------------------------------------------------------------------------
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::OnPaint()
{
	CMatRenderContextPtr pRenderContext( materials );

	// We want the models to use their natural alpha, not depth in alpha
	pRenderContext->SetIntRenderingParameter( INT_RENDERPARM_WRITE_DEPTH_TO_DESTALPHA, 0 );

	// draw commands

	// Run through and actually execute all of our draw commands
	for ( CUI_Canvas_DrawCommand *pCmd = m_pDrawCommands; pCmd != nullptr; pCmd = pCmd->m_pNext )
	{
		pCmd->Execute( pRenderContext );
	}

	pRenderContext->Flush();
}

//-----------------------------------------------------------------------------
// called when we're ticked...
//-----------------------------------------------------------------------------
void CUI_CanvasRenderer::OnTick()
{
	// time
	float flCurrentTime = UI_GetAutoPlayTime();

	m_flAutoPlayTimeBase = flCurrentTime;
}
