#!/usr/bin/env python3
"""Build the small D3D9 CSM instance shader in Distrobox dev (vkd3d-compiler)."""
import os
from pathlib import Path
import struct
import subprocess
import sys
import tempfile


def main():
    if os.environ.get("CONTAINER_ID") != "dev":
        os.execvp("distrobox", ["distrobox", "enter", "-T", "-n", "dev", "--",
                                "python3", str(Path(__file__).resolve()), *sys.argv[1:]])
    root = Path(__file__).resolve().parent.parent
    source = root / "src/materialsystem/shaderapidx9/csm_instancing_vs.hlsl"
    output = source.with_suffix(".inc")
    with tempfile.TemporaryDirectory(prefix="csgo-csm-shader-") as tmp:
        binary = Path(tmp) / "shader.bin"
        subprocess.run(["vkd3d-compiler", "-x", "hlsl", "-b", "d3dbc", "-p", "vs_3_0",
                        "--strip-debug", "-o", str(binary), str(source)], check=True)
        data = binary.read_bytes()
        if len(data) % 4 or struct.unpack_from("<I", data)[0] != 0xfffe0300:
            raise RuntimeError("Compiler did not produce a vs_3_0 shader")
        words = struct.unpack("<" + "I" * (len(data) // 4), data)
        lines = ["// Generated by scripts/build-csm-instance-shader.py; do not edit.",
                 "static const DWORD s_CSMInstancingVertexShader[] =", "{"]
        for i in range(0, len(words), 6):
            lines.append("\t" + ", ".join(f"0x{word:08x}" for word in words[i:i + 6]) + ",")
        lines.extend(["};", ""])
        output.write_text("\n".join(lines))
        subprocess.run(["vkd3d-compiler", "-x", "d3dbc", "-b", "d3d-asm", str(binary)], check=True)
    print(f"Generated {output.relative_to(root)} ({len(data)} bytes)")


if __name__ == "__main__":
    main()
