/* Generated by configure.  Do not edit. */
#ifndef CAIRO_FEATURES_H
#define CAIRO_FEATURES_H

// change by SLA 1/15/09
// #define CAIRO_HAS_FT_FONT 1
// #define CAIRO_HAS_IMAGE_SURFACE 1
// #define CAIRO_HAS_PDF_SURFACE 1
// #define CAIRO_HAS_PNG_FUNCTIONS 1
// #define CAIRO_HAS_PS_SURFACE 1
// #define CAIRO_HAS_SVG_SURFACE 1
// #define CAIRO_HAS_USER_FONT 1
// #define CAIRO_HAS_XLIB_SURFACE 1
// #define CAIRO_HAS_XLIB_XRENDER_SURFACE 1

#ifdef  __cplusplus
# define CAIRO_BEGIN_DECLS  extern "C" {
# define CAIRO_END_DECLS    }
#else
# define CAIRO_BEGIN_DECLS
# define CAIRO_END_DECLS
#endif
 
#ifndef cairo_public
#ifdef LIBCAIRO_EXPORTS
#define cairo_public __declspec(dllexport)
#else
#define cairo_public __declspec(dllimport)
#endif
#endif

#define HAVE_WINDOWS_H 1

#define CAIRO_HAS_SVG_SURFACE 1
#define CAIRO_HAS_PDF_SURFACE 1
#define CAIRO_HAS_PS_SURFACE 1
#define CAIRO_HAS_WIN32_SURFACE 1
#define CAIRO_HAS_WIN32_FONT 1
#define CAIRO_HAS_PNG_FUNCTIONS 1

/*#undef CAIRO_HAS_QUARTZ_FONT */
/*#undef CAIRO_HAS_QUARTZ_SURFACE */
/*#undef CAIRO_HAS_WIN32_FONT */
/*#undef CAIRO_HAS_WIN32_SURFACE */

#endif
